### ISSUE TITLE
How to use the javascript with Webpacker

### ISSUE THREAD

**Issue by DriftingShadows** [gregschmit/recurring_select#125]
I recently started using webpacker instead of the asset pipeline which makes the popup modal not work. How would I implement recurring select with webpacker?

**Comment by xilefff** [comment]
Hey! Is the recurring_select object getting istantiated correctly? I had a similar problem, solved with a small fork.

Try adding this in your Gemfile:
```
gem 'recurring_select', git: 'https://github.com/xilefff/recurring_select.git'
```

**Comment by cseelus** [comment]
How do you include the assets from this gem (stylesheet, JS) with webpacker?

**Comment by stramec** [comment]
@cseelus, did you ever figure this out?

**Comment by cseelus** [comment]
@stramec Nope, I just put together a [.js.erb](https://gist.github.com/cseelus/f79487b3dbcd9dc32d8ea76765ce5ce6) and [.scss](https://gist.github.com/cseelus/d5b6898bf356b56d5c88f6f7de6bd874) file from this repos `assets` folder, put them inside the `vendor` folders for Weppack assets I already had and included them in my packs.

**Comment by adebnar** [comment]
@cseelus do you have any additional information on your configuration? I've added the to files to the vendor folder and made sure `vendor` is added to the `webpacker.yml`. I see the files are built but the modal still does not launch.

I added 
/app/assets/stylesheets/application.scss
`*= require recurring_select`

/app/assets/javascripts/application.js
`//= require recurring_select`

**Comment by cseelus** [comment]
@adebnar I think with webpacker you need to import those files. I did it like this:

application.js pack:
```js
import '../vendor/javascripts/recurring-select.js.erb'
```

applicsation.sass pack:
```sass
@import '../vendor/stylesheets/recurring-select'
```

**Comment by gregschmit** [comment]
This project should not provide webpacker/shakapacker assets, as it's unnecessary.
